# Generated by Django 5.0.6 on 2024-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anonymity',
            field=models.BooleanField(default=True),
        ),
    ]
