# Generated by Django 5.0.6 on 2024-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymity',
            field=models.BooleanField(default=True),
        ),
    ]
