# Generated by Django 5.0.3 on 2024-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_phone_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
